{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: studio-postgresql
  labels:
    {{- include "studio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "studio-postgres.selectorLabels" . | nindent 4 }}
{{- end }}
